services:
  camunda-postgres:
    image: postgres:latest
    container_name: camunda-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - camunda-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  camunda-bpm:
    build: .
    container_name: camunda-bpm
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://camunda-postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - camunda-postgres
    networks:
      - camunda-net
    volumes:
      - ./web.xml:/camunda/webapps/engine-rest/WEB-INF/web.xml

  pg-backup:
    image: postgres:latest
    container_name: pg-backup
    depends_on:
      - camunda-postgres
    volumes:
      - postgres-backup:/backups
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    entrypoint: ["sh", "-c", "while true; do PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h camunda-postgres -p 5432 -U $POSTGRES_USER $POSTGRES_DB > /backups/backup.sql; sleep 3600; done"]
    networks:
      - camunda-net

networks:
  camunda-net:

volumes:
  postgres-data:
  postgres-backup:
